#!/usr/bin/env bash
# Setzt oder aendert das Passwort fuer die Recovery-Webseite (Basic-Auth).
# Aktualisiert .env, auth.snippet und reloaded Caddy live.

set -euo pipefail

REPO_DIR="/opt/homelab-dns"
ENV_FILE="$REPO_DIR/compose/.env"
SNIPPET="$REPO_DIR/compose/auth.snippet"

[[ $EUID -eq 0 ]] || { echo "Bitte als root ausfuehren: sudo $0"; exit 1; }
[[ -f "$ENV_FILE" ]] || { echo "FEHLER: $ENV_FILE fehlt — bootstrap zuerst ausfuehren"; exit 1; }

read -srp "Neues Passwort (min. 6 Zeichen, leer = Auth deaktivieren): " PW1
echo
if [[ -n "$PW1" ]]; then
    [[ ${#PW1} -ge 6 ]] || { echo "FEHLER: zu kurz"; exit 1; }
    read -srp "Passwort wiederholen: " PW2
    echo
    [[ "$PW1" == "$PW2" ]] || { echo "FEHLER: Passwoerter stimmen nicht ueberein"; exit 1; }

    HASH=$(python3 -c "import bcrypt; print(bcrypt.hashpw('$PW1'.encode(), bcrypt.gensalt(rounds=10)).decode())")

    {
        grep -v '^RECOVERY_PASSWORD_HASH=' "$ENV_FILE" 2>/dev/null
        printf 'RECOVERY_PASSWORD_HASH=%s\n' "$HASH"
    } > "${ENV_FILE}.tmp" && mv "${ENV_FILE}.tmp" "$ENV_FILE"
    chmod 0600 "$ENV_FILE"

    cat > "$SNIPPET" <<EOF
# auto-generated by set-password.sh
basic_auth /* {
	admin $HASH
}
EOF
    echo "Passwort gesetzt. Lade Caddy neu..."
else
    {
        grep -v '^RECOVERY_PASSWORD_HASH=' "$ENV_FILE" 2>/dev/null
        printf 'RECOVERY_PASSWORD_HASH=\n'
    } > "${ENV_FILE}.tmp" && mv "${ENV_FILE}.tmp" "$ENV_FILE"
    chmod 0600 "$ENV_FILE"

    echo "# auth disabled" > "$SNIPPET"
    echo "Auth deaktiviert. Lade Caddy neu..."
fi

if docker exec recovery-site caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile 2>/dev/null; then
    echo "Caddy reloaded."
else
    echo "Caddy reload fehlgeschlagen — Container wird neugestartet..."
    cd "$REPO_DIR/compose"
    docker compose restart recovery-site
fi
echo "Fertig."
